### ISSUE TITLE
Allow custom (un)serializer for a DB layer

### ISSUE THREAD

**Issue by yedpodtrzitko** [benediktschmitt/py-jsonapi#7]
Hi,
thanks for this great library.

I am currently using my custom fork (unfortunately, the project I work on is Python 2), but here's one thing which could be handy to have in the project.

I use DynamoDB as the project's DB with [PynamoDB](https://github.com/jlafon/PynamoDB) library, and its interface it's quite different than all the existing DB layers in the projects. So I created a bindings for it (`jsonapi.pynamodb`) and I have my own `Serializer`, `Unserializer`, `Schema` too + I dont need the `Database` object at all (since all db operations are dispatches via the models directly).  
Right now when I want to use a custom (un)serializer, I can define it per-model like this:

```python
api.add_type(PynamoDBSchema(PynamoDBModel, 'modelalias'), unserializer=CustomUnserializer, serializer=CustomSerializer)
```

This gets old quite fast, and it would be handy to have a custom `Serializer` and `Unserializer` per-database instead (as I would expect all the models will use the same serializers by default anyway).

So in my fork I do this:
```python
api = flask.FlaskAPI(MODEL_PREFIX, db=DummyObject(), dblayer=jsonschema.pynamodb)
```
and deep inside the `API` class (which is `FlaskAPI` inherited from) I do something like this:

```pytho
def __init__(self, uri, db, debug=False, settings=None, dblayer=None):
    ...
    if not dblayer:
        from jsonapi import base as dblayer

    self._serializer_class = dblayer.serializer.Serializer
    self._unserializer_class = dblayer.serializer.Unserializer
```

Cheers,
yed

**Comment by benediktschmitt** [comment]
Hi, I'm currently writing on version 1.0.0, which will make the db layer obsolete by introducing an Encoder and Decoder class.

**Comment by yedpodtrzitko** [comment]
Hi, thanks for your response. I'm gonna close this then.
